version: '3'

services:
  webpacker_dev:
    build: rails
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - ./rails:/srv/coral
      - gem_cache:/var/lib/ruby/gems
    env_file:
      - .docker-env/development/database
      - .docker-env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - coral_net

volumes:
  gem_cache:

networks:
  coral_net:
    external: true
