version: '3'

services:
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"
    networks:
      - coral_net

networks:
  coral_net:
    external: true
